# Generated by Django 5.2.7 on 2026-02-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("menopause", models.CharField(max_length=20)),
                ("tumor_size", models.IntegerField()),
                ("inv_nodes", models.IntegerField()),
                ("node_caps", models.CharField(max_length=10)),
                ("deg_malig", models.IntegerField()),
                ("breast", models.CharField(max_length=10)),
                ("breast_quad", models.CharField(max_length=20)),
                ("irradiation", models.CharField(max_length=10)),
                ("prediction", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
            ],
        ),
    ]
